-- marker: rhoai3.baseline-data/v1
-- GENERATED by bootstrap-destination. Do not edit: the bootstrap refuses a
-- hand-edited copy rather than overwrite it, and regenerates this file when
-- the contract below changes. Fix the declared dataset or the schema asset.
--
-- The destination's initialized logical data, derived from the baseline the
-- application contract declares, so the destination starts every parity
-- comparison from the state the source was captured in (ADR-009).
--
-- translator: baseline-data-translator/1.0.0
-- contract-sha256: da359b9e4610178708f168f76ed77ddd7ab40afe9813039dfe8fbc2303d8a907
-- destination-engine: postgresql
-- declared-dataset: src/main/resources/db/hsqldb/populateDB.sql
-- declared-dataset-sha256: 6d6fd4f158668638aa367f351795aa585d386b32bc8c727ead6417033d04a105
-- declared-dataset-named-by: corpus derived_from.seed
-- schema-asset: src/main/resources/db/postgresql/initDB.sql
-- schema-asset-sha256: e09b38c29e330a2c455490664b1c2f32f88c3c415d26488a998a2cfec9867ccd
-- rows: owners=10, pets=13, roles=3, specialties=3, types=6, users=1, vet_specialties=5, vets=6, visits=4
-- sequences: vets.id=6, specialties.id=3, types.id=6, owners.id=10, pets.id=13, visits.id=4, roles.id=(from the loaded rows)

-- the declared dataset, statement for statement, translated for this engine
INSERT INTO "vets" VALUES (1, 'James', 'Carter');
INSERT INTO "vets" VALUES (2, 'Helen', 'Leary');
INSERT INTO "vets" VALUES (3, 'Linda', 'Douglas');
INSERT INTO "vets" VALUES (4, 'Rafael', 'Ortega');
INSERT INTO "vets" VALUES (5, 'Henry', 'Stevens');
INSERT INTO "vets" VALUES (6, 'Sharon', 'Jenkins');
INSERT INTO "specialties" VALUES (1, 'radiology');
INSERT INTO "specialties" VALUES (2, 'surgery');
INSERT INTO "specialties" VALUES (3, 'dentistry');
INSERT INTO "vet_specialties" VALUES (2, 1);
INSERT INTO "vet_specialties" VALUES (3, 2);
INSERT INTO "vet_specialties" VALUES (3, 3);
INSERT INTO "vet_specialties" VALUES (4, 2);
INSERT INTO "vet_specialties" VALUES (5, 1);
INSERT INTO "types" VALUES (1, 'cat');
INSERT INTO "types" VALUES (2, 'dog');
INSERT INTO "types" VALUES (3, 'lizard');
INSERT INTO "types" VALUES (4, 'snake');
INSERT INTO "types" VALUES (5, 'bird');
INSERT INTO "types" VALUES (6, 'hamster');
INSERT INTO "owners" VALUES (1, 'George', 'Franklin', '110 W. Liberty St.', 'Madison', '6085551023');
INSERT INTO "owners" VALUES (2, 'Betty', 'Davis', '638 Cardinal Ave.', 'Sun Prairie', '6085551749');
INSERT INTO "owners" VALUES (3, 'Eduardo', 'Rodriquez', '2693 Commerce St.', 'McFarland', '6085558763');
INSERT INTO "owners" VALUES (4, 'Harold', 'Davis', '563 Friendly St.', 'Windsor', '6085553198');
INSERT INTO "owners" VALUES (5, 'Peter', 'McTavish', '2387 S. Fair Way', 'Madison', '6085552765');
INSERT INTO "owners" VALUES (6, 'Jean', 'Coleman', '105 N. Lake St.', 'Monona', '6085552654');
INSERT INTO "owners" VALUES (7, 'Jeff', 'Black', '1450 Oak Blvd.', 'Monona', '6085555387');
INSERT INTO "owners" VALUES (8, 'Maria', 'Escobito', '345 Maple St.', 'Madison', '6085557683');
INSERT INTO "owners" VALUES (9, 'David', 'Schroeder', '2749 Blackhawk Trail', 'Madison', '6085559435');
INSERT INTO "owners" VALUES (10, 'Carlos', 'Estaban', '2335 Independence La.', 'Waunakee', '6085555487');
INSERT INTO "pets" VALUES (1, 'Leo', '2010-09-07', 1, 1);
INSERT INTO "pets" VALUES (2, 'Basil', '2012-08-06', 6, 2);
INSERT INTO "pets" VALUES (3, 'Rosy', '2011-04-17', 2, 3);
INSERT INTO "pets" VALUES (4, 'Jewel', '2010-03-07', 2, 3);
INSERT INTO "pets" VALUES (5, 'Iggy', '2010-11-30', 3, 4);
INSERT INTO "pets" VALUES (6, 'George', '2010-01-20', 4, 5);
INSERT INTO "pets" VALUES (7, 'Samantha', '2012-09-04', 1, 6);
INSERT INTO "pets" VALUES (8, 'Max', '2012-09-04', 1, 6);
INSERT INTO "pets" VALUES (9, 'Lucky', '2011-08-06', 5, 7);
INSERT INTO "pets" VALUES (10, 'Mulligan', '2007-02-24', 2, 8);
INSERT INTO "pets" VALUES (11, 'Freddy', '2010-03-09', 5, 9);
INSERT INTO "pets" VALUES (12, 'Lucky', '2010-06-24', 2, 10);
INSERT INTO "pets" VALUES (13, 'Sly', '2012-06-08', 1, 10);
INSERT INTO "visits" VALUES (1, 7, '2013-01-01', 'rabies shot');
INSERT INTO "visits" VALUES (2, 8, '2013-01-02', 'rabies shot');
INSERT INTO "visits" VALUES (3, 8, '2013-01-03', 'neutered');
INSERT INTO "visits" VALUES (4, 7, '2013-01-04', 'spayed');
INSERT INTO "users" ("username", "password", "enabled") VALUES ('admin', '{noop}admin', true);
INSERT INTO "roles" ("username", "role") VALUES ('admin', 'ROLE_OWNER_ADMIN');
INSERT INTO "roles" ("username", "role") VALUES ('admin', 'ROLE_VET_ADMIN');
INSERT INTO "roles" ("username", "role") VALUES ('admin', 'ROLE_ADMIN');

-- every generated-identity column the destination schema declares continues
-- from the seeded maximum, the way the engine the source ran on did
SELECT setval(pg_get_serial_sequence('vets', 'id'), COALESCE((SELECT max("id") FROM "vets"), 1), (SELECT count(*) > 0 FROM "vets"));
SELECT setval(pg_get_serial_sequence('specialties', 'id'), COALESCE((SELECT max("id") FROM "specialties"), 1), (SELECT count(*) > 0 FROM "specialties"));
SELECT setval(pg_get_serial_sequence('types', 'id'), COALESCE((SELECT max("id") FROM "types"), 1), (SELECT count(*) > 0 FROM "types"));
SELECT setval(pg_get_serial_sequence('owners', 'id'), COALESCE((SELECT max("id") FROM "owners"), 1), (SELECT count(*) > 0 FROM "owners"));
SELECT setval(pg_get_serial_sequence('pets', 'id'), COALESCE((SELECT max("id") FROM "pets"), 1), (SELECT count(*) > 0 FROM "pets"));
SELECT setval(pg_get_serial_sequence('visits', 'id'), COALESCE((SELECT max("id") FROM "visits"), 1), (SELECT count(*) > 0 FROM "visits"));
SELECT setval(pg_get_serial_sequence('roles', 'id'), COALESCE((SELECT max("id") FROM "roles"), 1), (SELECT count(*) > 0 FROM "roles"));
