#!/usr/bin/env bash
# Restore the decided datasource's isolated instance to the initial state the
# scenario corpus names: drop and recreate the schema, apply the schema asset
# decisions.yaml points at, load the DERIVED baseline data, align every
# generated-identity sequence, and then VERIFY that the baseline the asset
# declares is the baseline the database now holds.
#
# The reset is part of the evidence, not a convenience. A scenario that
# declares reset_before is only meaningful if the state it starts from is the
# state the corpus says it is, and an effect probe on a mutated database
# proves nothing. Credentials come from the environment by the names the
# decision records; nothing here reads or prints a secret.
#
# What it loads changed with ADR-009's baseline-state correction. The engine is
# a decision; the DATA is not. Loading the source's own per-engine seed made
# the destination start from a dataset the corpus never declared -- measured on
# the specimen: 17 different date literals, and a schema that restarts seven
# identity sequences at a fixed 100 where the engine the source was captured on
# continued from the seeded maximum. So the reset loads
# src/main/resources/db/<engine>/baseline-data.sql, which bootstrap-destination
# DERIVES from the declared dataset, and then asserts the row counts and the
# sequence positions inside the database. A tree with no derived asset (an
# older bootstrap) keeps the previous behaviour and says the baseline is
# unverified, which is a fact about the run and belongs in its log.
#
# It talks JDBC through the destination's own driver rather than a command-line
# client: the workspace that runs the comparison has a JDK and that driver on
# disk, and no psql. A reset that cannot run would turn every reset_before
# scenario INCONCLUSIVE, which is a tooling gap masquerading as a finding. The
# verification is therefore SQL the database itself raises on, generated by
# .hermes/skills/migration/bootstrap-destination/scripts/_baseline_data.py --
# the same module that wrote the asset, and the same judgement its
# verify_observations() makes over query results in the selftest.
#
# Fixture variants (ADR-014). --variant NAME resets to the same verified
# baseline and then applies the statements decisions.yaml declares under
# security.fixtures[NAME] -- a database state the declared dataset does not
# have, such as an identity the seed enables being disabled. The order is the
# point: the baseline is loaded and VERIFIED first, so the variant is
# demonstrably the declared baseline plus those statements and not some other
# state that happens to answer the same way. The statements are the
# specimen's own SQL and nothing here parses them. Restoring the baseline
# afterwards is this same script with no --variant, which loads the baseline
# and verifies it -- the restoration ADR-014 asks for, proved rather than
# assumed.
#
#   reset-parity-db.sh --root /projects/modernized [--driver /path/to/driver.jar]
#   reset-parity-db.sh --root /projects/modernized --print-plan
#   reset-parity-db.sh --root /projects/modernized --variant identity-disabled
#   reset-parity-db.sh --root /projects/modernized --revert-variant identity-disabled
#
# --revert-variant NAME is the other half of REVERT-THEN-READ (a refused
# variant write whose state no other declared identity can read): it loads
# nothing and drops nothing; it executes ONLY the revert the derivation
# computed for that variant (recorded in the variant corpus, read through the
# corpus loader so an edited plan is refused), inside one block that first
# proves it finds the variant state -- the fixture's table still holds the
# baseline's row count, the predicate selects the baseline's rows, and those
# rows hold the variant value -- then updates exactly those rows and proves
# they hold the baseline value. Anything else raises and changes nothing. The
# fixture statements the corpus was derived from must still be the ones
# decisions.yaml declares.
#
# Exit 0 reset (and verified, when there is a derived baseline), 1 refused, 2 usage.
set -euo pipefail
ROOT=""
DRIVER=""
PRINT_PLAN="no"
VARIANT=""
REVERT=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --root) ROOT="${2:-}"; shift 2 ;;
    --driver) DRIVER="${2:-}"; shift 2 ;;
    --variant) VARIANT="${2:-}"; shift 2 ;;
    --revert-variant) REVERT="${2:-}"; shift 2 ;;
    --print-plan) PRINT_PLAN="yes"; shift ;;
    *) echo "usage: reset-parity-db.sh --root <dest> [--driver <jar>] [--variant <name> | --revert-variant <name>] [--print-plan]" >&2; exit 2 ;;
  esac
done
[[ -n "${ROOT}" && -d "${ROOT}" ]] || { echo "FAIL: --root must be an existing directory" >&2; exit 2; }
[[ -z "${VARIANT}" || -z "${REVERT}" ]] || { echo "FAIL: --variant sets a variant and --revert-variant reverts one; pass one" >&2; exit 2; }
ROOT="$(cd "${ROOT}" && pwd)"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASELINE_TOOL="${HERE}/../../../migration/bootstrap-destination/scripts/_baseline_data.py"

# WHOSE DATABASE IS THIS? Asked here, before a driver is found, before a
# credential is read and long before a connection is opened.
#
# The architect drove this script on 2026-09-22 with an UNSTAMPED destination
# and with another run's URL. Both reached the Java reset runner, which drops
# and recreates the public schema without any run binding: the only reason no
# data was lost is that java was stubbed for the experiment. A refusal that
# happens at M2 admission is not a refusal at the operation that connects.
#
# planner.run_identity PARSES the endpoint -- engine, host, port, database --
# and compares each field with the assignment the platform issued for this run
# and with the receipt the platform wrote into this workspace. A wrong
# namespace, a wrong database, a host that merely starts with the right name
# and a host carrying the right name only in a query parameter are four
# different endpoints and all four are refused. --print-plan reads decisions
# and touches nothing, so it is judged as analysis: it still refuses a wrong
# target and still prints against a target that does not exist yet.
OWNERSHIP_OP="reset"
[[ -z "${VARIANT}" ]] || OWNERSHIP_OP="fixture"
[[ -z "${REVERT}" ]] || OWNERSHIP_OP="revert"
[[ "${PRINT_PLAN}" != "yes" ]] || OWNERSHIP_OP="analysis"
PYTHONPATH="${ROOT}/.hermes/lib${PYTHONPATH:+:${PYTHONPATH}}" \
  python3 -m planner.run_identity --root "${ROOT}" --operation "${OWNERSHIP_OP}" \
  || { echo "FAIL: RESET refused before connecting: this destination is not bound to its own parity database (above)" >&2; exit 1; }

WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT

read -r DB_KIND URL_ENV USER_ENV PASS_ENV SCHEMA_SQL SEED_SQL < <(python3 - "${ROOT}" <<'PYEOF'
import sys
from pathlib import Path
root = Path(sys.argv[1])
sys.path.insert(0, str(root / ".hermes" / "lib"))
from planner.decisions import datasource, load_decisions
ds = datasource(load_decisions(root))
if not ds:
    raise SystemExit("FAIL: RESET the effective datasource is not decided in decisions.yaml")
print(" ".join(str(ds.get(k) or "-") for k in ("db_kind", "jdbc_url_env", "username_env", "password_env", "schema_sql", "seed_sql")))
PYEOF
)

if [[ -n "${REVERT}" ]]; then
  [[ "${DB_KIND}" == "postgresql" ]] || { echo "FAIL: RESET REVERT_ENGINE the revert is written for postgresql and the decided datasource is ${DB_KIND}" >&2; exit 1; }
  REVERT_ROWS="$(python3 - "${ROOT}" "${REVERT}" "${WORK}/revert.sql" "${HERE}" 2>"${WORK}/revert.err" <<'PYEOF'
import sys
from pathlib import Path
root, name, out, here = Path(sys.argv[1]), sys.argv[2], Path(sys.argv[3]), sys.argv[4]
sys.path.insert(0, here)
sys.path.insert(0, str(root / ".hermes" / "lib"))
import _variant_revert as vr
from _scenarios import DEFAULT_SECURITY_MODE, SECURITY_MODES, CorpusError, corpus_path, load_corpus
from planner.decisions import load_decisions, security
corpus, why = None, []
for mode in SECURITY_MODES:
    if mode == DEFAULT_SECURITY_MODE or not (root / corpus_path(mode, name)).is_file():
        continue
    try:
        corpus = load_corpus(root, mode, name)
        break
    except CorpusError as exc:
        why.append(str(exc))
if corpus is None:
    raise SystemExit("REVERT_NO_CORPUS no usable variant corpus for %r%s" % (name, (": " + "; ".join(why)) if why else ""))
fixture = corpus.get("fixture") or {}
plan = fixture.get("revert")
gap = vr.plan_gap(plan)
if gap:
    raise SystemExit("REVERT_NO_PLAN the %s variant corpus carries no executable revert (%s)%s"
                     % (name, gap, ("; the derivation said: " + fixture["revert_refused"]) if fixture.get("revert_refused") else ""))
decided = security(load_decisions(root)) or {}
rows = [f for f in (decided.get("fixtures") or []) if f.get("name") == name]
if not rows or [str(s).strip() for s in rows[0]["statements"]] != [str(s).strip() for s in (fixture.get("statements") or [])]:
    raise SystemExit("REVERT_STALE_PLAN decisions.yaml no longer declares the statements the %s revert was computed from; "
                     "derive the variant again" % name)
out.write_text(vr.revert_sql(plan), encoding="utf-8")
print(len(plan["rows"]))
PYEOF
)" || { echo "FAIL: RESET the ${REVERT} revert is unusable: $(tr '\n' ' ' <"${WORK}/revert.err")" >&2; exit 1; }
  if [[ "${PRINT_PLAN}" == "yes" ]]; then
    echo "plan: revert ${DB_KIND} from ${URL_ENV} (credentials ${USER_ENV}/${PASS_ENV}); nothing dropped, nothing loaded"
    echo "revert: fixture ${REVERT} (${REVERT_ROWS} computed row revert(s) from the variant corpus)"
    echo "verify: before -- the table's baseline row count, the predicate's baseline rows, the variant value on each; after -- exactly those rows updated, each holding the baseline value; otherwise nothing changes"
    sed 's/^/sql: /' "${WORK}/revert.sql"
    exit 0
  fi
fi

if [[ -z "${REVERT}" ]]; then
# The derived baseline, when this tree has one: what to load after the schema,
# and what must then be true. Exit 3 says the tree predates it.
BASELINE_FACTS=""
BASELINE_REL=""
BASELINE_RC=0
if [[ -f "${BASELINE_TOOL}" ]]; then
  BASELINE_FACTS="$(python3 "${BASELINE_TOOL}" --root "${ROOT}" --emit-verify "${WORK}/baseline-verify.sql" 2>"${WORK}/baseline.err")" || BASELINE_RC=$?
else
  BASELINE_RC=3
  echo "no baseline translator beside this script (${BASELINE_TOOL})" >"${WORK}/baseline.err"
fi
if [[ "${BASELINE_RC}" == "0" ]]; then
  BASELINE_REL="$(printf '%s\n' "${BASELINE_FACTS}" | sed -n 's/^baseline: //p' | head -1)"
elif [[ "${BASELINE_RC}" == "3" ]]; then
  echo "NOTE: RESET no derived baseline asset in this tree ($(tr -d '\n' <"${WORK}/baseline.err")); loading ${SEED_SQL} and NOT verifying the baseline"
else
  echo "FAIL: RESET the derived baseline asset is unusable: $(tr -d '\n' <"${WORK}/baseline.err")" >&2
  exit 1
fi

SQL_RELS=()
if [[ "${SCHEMA_SQL}" != "-" ]]; then
  SQL_RELS+=("${SCHEMA_SQL}")
fi
if [[ -n "${BASELINE_REL}" ]]; then
  SQL_RELS+=("${BASELINE_REL}")
elif [[ "${SEED_SQL}" != "-" ]]; then
  SQL_RELS+=("${SEED_SQL}")
fi
SQL_FILES=()
for rel in ${SQL_RELS[@]+"${SQL_RELS[@]}"}; do
  [[ -f "${ROOT}/${rel}" ]] || { echo "FAIL: RESET decisions.yaml names ${rel}, which is not in the tree" >&2; exit 1; }
  SQL_FILES+=("${ROOT}/${rel}")
done
if [[ -n "${BASELINE_REL}" ]]; then
  SQL_FILES+=("${WORK}/baseline-verify.sql")
fi

# The declared variant's statements, read from the one file that may declare
# them. They go LAST -- after the baseline's own verification -- so what they
# vary is a baseline this run proved, and so a variant that cannot be read
# refuses before anything is applied.
VARIANT_COUNT=0
if [[ -n "${VARIANT}" ]]; then
  VARIANT_COUNT="$(python3 - "${ROOT}" "${VARIANT}" "${WORK}/variant.sql" 2>"${WORK}/variant.err" <<'PYEOF'
import sys
from pathlib import Path
root, name, out = Path(sys.argv[1]), sys.argv[2], Path(sys.argv[3])
sys.path.insert(0, str(root / ".hermes" / "lib"))
from planner.decisions import load_decisions, security, security_gaps
doc = load_decisions(root)
decided = security(doc)
if not decided:
    refusals = security_gaps(doc)
    raise SystemExit("decisions.yaml declares no usable security section%s"
                     % ((": " + "; ".join("%s %s" % (g["subject"], g["detail"]) for g in refusals)) if refusals else ""))
rows = [f for f in (decided.get("fixtures") or []) if f.get("name") == name]
if not rows:
    raise SystemExit("decisions.yaml declares no security fixture named %r (it declares: %s)"
                     % (name, ", ".join(str(f.get("name")) for f in (decided.get("fixtures") or [])) or "none"))
statements = [str(s).strip() for s in rows[0]["statements"]]
# opaque SQL: applied exactly as declared, terminated so the runner reads
# each as a statement, under a comment naming where it came from
out.write_text("-- decisions.security.fixtures[%s]\n" % name
               + "".join((s if s.endswith(";") else s + ";") + "\n" for s in statements), encoding="utf-8")
print(len(statements))
PYEOF
)" || { echo "FAIL: RESET the fixture variant ${VARIANT} is unusable: $(tr '\n' ' ' <"${WORK}/variant.err")" >&2; exit 1; }
  SQL_FILES+=("${WORK}/variant.sql")
fi

if [[ "${PRINT_PLAN}" == "yes" ]]; then
  echo "plan: reset ${DB_KIND} from ${URL_ENV} (credentials ${USER_ENV}/${PASS_ENV})"
  for rel in ${SQL_RELS[@]+"${SQL_RELS[@]}"}; do echo "apply: ${rel}"; done
  if [[ -n "${BASELINE_REL}" ]]; then
    printf '%s\n' "${BASELINE_FACTS}" | sed -n '2,$p'
    echo "verify: row counts per table and each aligned sequence's next value = max + 1"
  else
    echo "verify: none (no derived baseline asset; the baseline is unverified)"
  fi
  if [[ -n "${VARIANT}" ]]; then
    echo "apply: fixture ${VARIANT} (${VARIANT_COUNT} statement(s) from decisions.yaml security.fixtures[${VARIANT}], after the verified baseline)"
    echo "restore: reset-parity-db.sh --root ${ROOT} (loads the baseline again and verifies it)"
  fi
  exit 0
fi
fi  # not a revert

URL="${!URL_ENV:-}"
DB_USER="${!USER_ENV:-}"
DB_PASSWORD="${!PASS_ENV:-}"
[[ -n "${URL}" && -n "${DB_USER}" && -n "${DB_PASSWORD}" ]] || { echo "FAIL: RESET ${URL_ENV}, ${USER_ENV} and ${PASS_ENV} must be set (the decision references them by name)" >&2; exit 1; }

# The driver, found under its OWN group directory. A bare artifact glob is not
# a driver: ~/.m2 also holds org.testcontainers:postgresql, which matched
# postgresql-*.jar and produced "No suitable driver found".
if [[ -z "${DRIVER}" ]]; then
  case "${DB_KIND}" in
    postgresql) GROUP_DIR="org/postgresql/postgresql" ;;
    mysql) GROUP_DIR="com/mysql/mysql-connector-j" ;;
    mariadb) GROUP_DIR="org/mariadb/jdbc/mariadb-java-client" ;;
    mssql) GROUP_DIR="com/microsoft/sqlserver/mssql-jdbc" ;;
    h2) GROUP_DIR="com/h2database/h2" ;;
    *) echo "FAIL: RESET no driver coordinate for db_kind ${DB_KIND}; pass --driver" >&2; exit 1 ;;
  esac
  DRIVER="$(find "${HOME}/.m2/repository/${GROUP_DIR}" -name "*.jar" ! -name "*sources*" ! -name "*javadoc*" 2>/dev/null | sort -V | tail -1)"
fi
[[ -n "${DRIVER}" && -f "${DRIVER}" ]] || { echo "FAIL: RESET no ${DB_KIND} JDBC driver found under ~/.m2; pass --driver <jar>" >&2; exit 1; }

javac -d "${WORK}" "${HERE}/reset-db/ResetDb.java" >"${WORK}/javac.log" 2>&1 || { echo "FAIL: RESET could not compile the reset runner: $(tail -3 "${WORK}/javac.log")" >&2; exit 1; }
# read the jar directly: `unzip -l | grep -q` closes the pipe on the first
# match, and under pipefail that reads as a failure (the same trap the stage
# validator hit)
REGISTERS="$(python3 -c 'import sys, zipfile; print("yes" if "META-INF/services/java.sql.Driver" in zipfile.ZipFile(sys.argv[1]).namelist() else "no")' "${DRIVER}" 2>/dev/null || echo no)"
if [[ "${REGISTERS}" != "yes" ]]; then
  echo "FAIL: RESET $(basename "${DRIVER}") registers no JDBC driver; pass --driver <jar>" >&2
  exit 1
fi
if [[ -n "${REVERT}" ]]; then
  java -cp "${DRIVER}:${WORK}" ResetDb "${URL}" "${DB_USER}" "${DB_PASSWORD}" --keep-schema "${WORK}/revert.sql" \
    || { echo "FAIL: RESET REVERT_UNEXPECTED_STATE the ${REVERT} revert did not find the variant state it reverts; nothing was changed" >&2; exit 1; }
  echo "OK: reverted the ${REVERT} fixture (${REVERT_ROWS} row revert(s)), found in the variant state and verified at the baseline values, using $(basename "${DRIVER}")"
  exit 0
fi
# A verification statement that does not hold RAISEs, the runner propagates the
# SQLException, and this script exits non-zero: an unverified baseline is never
# reported as a reset.
java -cp "${DRIVER}:${WORK}" ResetDb "${URL}" "${DB_USER}" "${DB_PASSWORD}" ${SQL_FILES[@]+"${SQL_FILES[@]}"}
VARIANT_NOTE=""
if [[ -n "${VARIANT}" ]]; then
  VARIANT_NOTE=", then the ${VARIANT} fixture's ${VARIANT_COUNT} statement(s)"
fi
if [[ -n "${BASELINE_REL}" ]]; then
  printf '%s\n' "${BASELINE_FACTS}" | sed -n '2,$p'
  echo "OK: reset to the DECLARED initial state and verified (${SQL_RELS[*]})${VARIANT_NOTE} using $(basename "${DRIVER}")"
else
  echo "OK: reset to the initial state (${SQL_RELS[*]})${VARIANT_NOTE} using $(basename "${DRIVER}"); baseline UNVERIFIED (no derived asset)"
fi
